# a simple DAO for a database that does CRUD operations on a books table
#author: Gerry Callaghan

import mysql.connector
from dbconfig import config_details

class BookDAO:

    host = config_details['host']
    user = config_details['user']
    password = config_details['password']
    database = config_details['database']
    connection = ""
    cursor = ""


    def get_cursor(self):
        self.connection = mysql.connector.connect(
            host=self.host,
            user=self.user,
            password=self.password,
            database=self.database
        )
        self.cursor = self.connection.cursor()
        return self.cursor

    def close_all(self):
        self.cursor.close()
        self.connection.close()

    # creating data in a database
    def create_book(self, book):
        mycursor = self.get_cursor()
        sql = "Insert into books1 (title, author, price) values (%s, %s,%s)"
        values = (book.get("title"), book.get("author"), book.get("price")) # get the title, author, and price out of the dictionary object, we use .get(" "). If not set, get will return None
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. The %s in the sql string are placeholders for the values that will be passed in the values tuple. This is a common way to prevent SQL injection attacks, as it ensures that the values are properly escaped before being inserted into the database.

        self.connection.commit() # this is necessary to save the changes to the database, if you don't call commit, the changes will not be saved and will be lost when the connection is closed.
        print("1 record inserted, ID:", mycursor.lastrowid)
        book["id"] = mycursor.lastrowid # we can NOW add the id to the book dictionary object that was passed in, so that when we return the book, it will have the NEW id that was just autogenerated by the database
        self.close_all()
        return book

    # reading data from a database
    def get_all_books(self):
        mycursor = self.get_cursor()
        sql = "Select * from books1"
        mycursor.execute(sql) 

        results = mycursor.fetchall() # this will return all records from the database as a list of tuples, where each tuple represents a record. If no records are found, it will return an empty list.
        book_list = []
        for result in results:
            book_list.append(self.convert_to_dict(result)) # this will convert each tuple in the results list to a dictionary object using the convert_to_dict() function, and then add that dictionary to the book_list. The convert_to_dict() function will take a tuple representing a book record and convert it to a dictionary with the keys being the column names and the values being the corresponding values for that record.

        self.close_all()
        return book_list

    # finding one book by id
    def find_book_by_id(self, bookid):
        mycursor = self.get_cursor()
        sql = "Select * from books1 where id = %s"
        values = (bookid,)

        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. The %s in the sql string are placeholders for the values that will be passed in the values tuple. This is a common way to prevent SQL injection attacks, as it ensures that the values are properly escaped before being inserted into the database.
        results = mycursor.fetchone() # this will return a single record from the database that matches the specified id, as a tuple. If no record is found, it will return None. If multiple records are found (which shouldn't happen if id is a primary key), it will return the first record that matches the criteria.
        #print(results)

        self.close_all()
        return self.convert_to_dict(results)

    # updating data in a database
    def update_book(self, bookid, book):
        book_to_be_updated= self.find_book_by_id(bookid)
        mycursor = self.get_cursor()
        sql = "Update books1 set title = %s, author = %s, price = %s where id = %s"
        values = (book.get("title"), book.get("author"), book.get("price"),bookid) # get the title, author, and price out of the dictionary object, we use .get(" "). If not set, get will return None
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. The %s in the sql string are placeholders for the values that will be passed in the values tuple. This is a common way to prevent SQL injection attacks, as it ensures that the values are properly escaped before being inserted into the database.
        self.connection.commit() # this is necessary to save the update to the database, if you don't call commit, the changes will not be saved and will be lost when the connection is closed.
        #updated_id = mycursor.lastrowid#
        #print("1 record updated, ID:", bookid, "new book details are:", book.get("title"), book.get("author"), book.get("price")) # this will print the id of the record that was updated so you know you updated the correct record 
        self.close_all()
        return book, book_to_be_updated # we can return the book that was just updated, so that we can see what was updated in the test output, and also return the original book before it was updated, so that we can see the difference in the test output

    # deleting data from a database
    def delete_book(self, bookid):
        book_to_be_deleted= self.find_book_by_id(bookid)
        mycursor = self.get_cursor()
        sql = "Delete from books1 where id = %s"
        values = (bookid,)
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. The %s in the sql string are placeholders for the values that will be passed in the values tuple. This is a common way to prevent SQL injection attacks, as it ensures that the values are properly escaped before being inserted into the database.
        self.connection.commit() # this is necessary to save the deletion to the database, if you don't call commit, the changes will not be saved and will be lost when the connection is closed.

        #print("1 record deleted")
        self.close_all()
        return True, book_to_be_deleted # we can return the book that was just deleted, so that we can see what was deleted in the test output

    def convert_to_dict(self, resultline):
        bookkeys = ["id", "title", "author", "price"]
        current_key = 0
        book = {}
        for attrib in resultline:
            book[bookkeys[current_key]] = attrib
            current_key += 1
        return book
        

bookDAO = BookDAO() # make an instance of the DAO class to use again
