# a simple DAO for a database that does CRUD operations on a books table
#author: Gerry Callaghan

import mysql.connector
from testing_dbconfig import config_details
#from dbconfig_pythonanywhere import config_details


class BookDAO:

    host = config_details['host']
    user = config_details['user']
    password = config_details['password']
    database = config_details['database']
    connection = ""
    cursor = ""


    def get_cursor(self):
        self.connection = mysql.connector.connect(
            host=self.host,
            user=self.user,
            password=self.password,
            database=self.database
        )
        self.cursor = self.connection.cursor()
        return self.cursor

    def close_all(self):
        self.cursor.close()
        self.connection.close()


    # creating data in a database
    def create_book(self, book):
        mycursor = self.get_cursor()# this creates a connection to the database and return a cursor object that we can use to execute SQL commands
        sql = "Insert into books1 (title, author, price) values (%s, %s,%s)"
        values = (book.get("title"), book.get("author"), book.get("price")) # .get(" ") pulls the title, author, and price FROM the dictionary object which is the format it is stored in the database. If not set, get will return None
       
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. 
        # The %s in the sql string are placeholders for the values that will be passed in the values tuple. This is a common way to prevent SQL injection attacks, 
        # because it ensures that the values are properly escaped before being inserted into the database.

        self.connection.commit() # this is necessary to save the changes to the database, if commit is not called, the changes will not be saved and will be lost when the connection is closed.
        #print("1 record inserted, ID:", mycursor.lastrowid) # this is just for testing, it will print the id of the record that was just inserted so you know it was inserted correctly. 
        # The lastrowid property of the cursor object will return the id of the last record that was inserted into the database, 
        # this is useful for confirming that the insert operation was successful and for retrieving the id of the new record if needed.
        
        book["id"] = mycursor.lastrowid # we can NOW add the id to the book dictionary object that was passed in, so that when we return the book, it will have the NEW id that was just autogenerated by the database
        self.close_all() # this will close the connection to the database, to free up resources and prevent potential issues with too many open connections simultaneously.
        return book


    # reading data from a database
    def get_all_books(self):
        mycursor = self.get_cursor()
        sql = "Select * from books1"
        
        mycursor.execute(sql) 
        results = mycursor.fetchall() # this will return all records from the database as a list of tuples, where each tuple represents a record. If no records are found, it will return an empty list.
        #print(results) # this is just for testing, it will print the record that was found, so you can confirm that all the records were retrieved from the database.

        book_list = []
        for result in results:
            book_list.append(self.convert_to_dict(result)) # this will convert each tuple in the results list to a dictionary object using the convert_to_dict() function 
    
        self.close_all()
        return book_list


    # finding one book by id
    def find_book_by_id(self, id):
        mycursor = self.get_cursor()
        sql = "Select * from books1 where id = %s"
        values = (id,)

        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. 
        results = mycursor.fetchone() # this will return a single record from the database that matches the specified id, as a tuple. 
        # If no record is found, it will return None. If multiple records are found (which shouldn't happen if id is a primary key), 
        # it will return the first record that matches the criteria.
        #print(results) # this is just for testing, it will print the record that was found, so you can confirm that the correct record was retrieved from the database.

        book_found = self.convert_to_dict(results) # this will convert the tuple returned by fetchone() to a dictionary object using the convert_to_dict() function, 
        # so that it can be easily returned in the JSON response.

        self.close_all()
        return book_found


    # updating data in a database
    def update_book(self, id, book):
        book_to_be_updated= self.find_book_by_id(id)
        mycursor = self.get_cursor()
        sql = "Update books1 set title = %s, author = %s, price = %s where id = %s"
        values = (book.get("title"), book.get("author"), book.get("price"),id) # use .get(" ")to get the title, author, and price out of the dictionary object. If not set, get will return None
        
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function
        self.connection.commit() # this is necessary to save the update to the database, if you don't call commit, the changes will not be saved and will be lost when the connection is closed.
        #updated_id = mycursor.lastrowid#
        #print("1 record updated, ID:", bookid, "new book details are:", book.get("title"), book.get("author"), book.get("price")) # this is for testing and prints the id of the record that was updated 
        # so you know you updated the correct record 

        self.close_all()
        return book, book_to_be_updated # we return the book that was just updated, so that we can see what was updated in the test output, 
        # and also return the original book before it was updated, so that we can see the difference in the test output

    # deleting data from a database
    def delete_book(self, id):
        book_to_be_deleted= self.find_book_by_id(id)
        mycursor = self.get_cursor()
        sql = "Delete from books1 where id = %s"
        values = (id,)
        
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function
        self.connection.commit() # this is necessary to save the deletion to the database, 
        #print("1 record deleted") # this is for testing and print a message to confirm that the record was deleted, so you know the delete operation was successful.

        self.close_all()
        return book_to_be_deleted # we can return the book that was just deleted, so that we can see what was deleted

    def convert_to_dict(self, resultline):  # this will convert each tuple in the results list to a dictionary object , 
            # This function will take in a tuple that represents a record from the database, and convert it to a dictionary object 
            # with the keys being the "column" names and the values being the corresponding values for each column for that record. 
             # This is useful because it allows us to easily return the data in a JSON response, which is a common format for APIs. 
        bookkeys = ["id", "title", "author", "price"]
        current_key = 0
        book = {} # set up an empty dictionary object to hold the key value pairs for the book record
        for attrib in resultline: # for each attribute in the tuple that represents the record, we will add a key value pair to the book dictionary object, 
            # where the key is the corresponding column name from the bookkeys list, and the value is the attribute from the tuple.
            book[bookkeys[current_key]] = attrib # this will add a key value pair to the book dictionary object, 
            # where the key is the corresponding column name from the list, and the value is the attribute for that column from the tuple.
            # First time through the loop, current_key will be 0, so the key will be "id" and the value will be the first attribute in the tuple (which is the id of the book).
            # second time through the loop, current_key will be 1, so the key will be "title" and the value will be the second attribute in the tuple (which is the title of the book), and so on for author and price.    
            current_key += 1
        return book
        

bookDAO = BookDAO() # make an instance of the DAO class to use again
